baseURL = "https://eduardohitek.dev/"
languageCode = "en-us"
paginate = 5
title = "Eduardo Hitek"
theme = "hello-friend"
disqusShortname = "blog-eduardohitek-com"
googleAnalytics = "UA-142179101-1"

[params]
  defaultTheme = "light"
  enableThemeToggle = true
  author = "Eduardo Hitek"
  description = "Software Developer."
  [[params.social]]
    name = "github"
    url = "https://github.com/eduardohitek"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/eduardohitek"
  [[params.social]]
    name = "dev"
    url = "http://dev.to/eduardohitek"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Eduardo Hitek"
    subtitle = "Personal Site and Blog"
    keywords = "software engineering, development, tutorials"
    # copyright = 'Eduardo Hitek'
    readOtherPosts = "Read other posts"
	dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01-2006"

    [languages.en.params.logo]
      logoText = "eduardo hitek"
      logoHomeLink = "/"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "english"
    name       = "Blog English"
    url        = "/posts-en"
